/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/18/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "http://examples.apimatic.io/apps/calculator"

};

module.exports = configuration;

